@startmindmap
'https://plantuml.com/mindmap-diagram

caption 基本情報技術者試験
title 試験範囲 Ver7.1

* FE
** テクノロジ系
*** 基礎理論
**** 基礎理論
***** 離散数学
***** 応用数学
***** 情報に関する理論
***** 通信に関する理論
***** 計測・制御に関する理論
**** アルゴリズムとプログラミング
***** データ構造
***** アルゴリズム
***** プログラミング
***** プログラム言語
***** その他言語

*** コンピュータシステム
**** コンピュータ構成要素
***** プロセッサ
***** メモリ
***** パス
***** 入出力デバイス
***** 入出力装置

**** システム構成要素
***** システムの構成
***** システムの評価指数

**** ソフトウェア
***** オペレーティングシステム
***** ミドルウェア
***** ファイルシステム
***** 開発ツール
***** オープンソースソフトウェア

**** ハードウェア
***** ハードウェア

*** 技術要素
**** ヒューマンインターフェース
***** ヒューマンインターフェース技術
***** インターフェース設計

**** マルチメディア
***** マルチメディア技術
***** マルチメディア応用

**** データベース
***** データベース方式
***** データベース設計
***** データ操作
***** トランザクション処理
***** データベース応用

**** ネットワーク
***** ネットワーク方式
***** データ通信と制御
***** 通信プロトコル
***** ネットワーク管理
***** ネットワーク応用

**** セキュリティ
***** 情報セキュリティ
***** 情報セキュリティ管理
***** セキュリティ技術評価
***** 情報セキュリティ対策
***** セキュリティ実装技術

*** 開発技術
**** システム開発技術
***** システム要件定義
***** システム方式設計
***** ソフトウェア要件定義
***** ソフトウェア方式設計・ソフトウェア詳細設計
***** ソフトウェア構築
***** ソフトウェア結合・ソフトウェア適格性確認テスト
***** システム結合・システム適格性確認テスト
***** 導入
***** 受け入れ支援
***** 保守・廃棄

**** ソフトウェア開発管理技術
***** 開発プロセス・手法
***** 知的財産適用管理
***** 開発環境管理
***** 構成管理・変更管理

** マネジメント系
*** プロジェクトマネジメント
**** プロジェクトマネジメント
***** プロジェクトマネジメント
***** プロジェクトの統合
***** プロジェクトのステークホルダ
***** プロジェクトのスコープ
***** プロジェクトの資源
***** プロジェクトの時間
***** プロジェクトのコスト
***** プロジェクトのリスク
***** プロジェクトの品質
***** プロジェクトの調達
***** プロジェクトのコミュニケーション

*** サービスマネジメント
**** サービスマネジメント
***** サービスマネジメント
***** サービスマネジメントシステムの計画及び運用
***** パフォーマンス評価及び改善
***** サービスの運用
***** ファシリティマネジメント

**** システム監査
***** システム監査
***** 内部統制


** ストラテジ系

*** システム戦略
**** システム戦略
***** 情報システム戦略
***** 業務プロセス
***** ソリューションビジネス
***** システム活用促進・評価

**** システム企画
***** システム化計画
***** システム要件定義
***** 調達計画・実施

*** 経営戦略
**** 経営戦略マネジメント
***** 経営戦略手法
***** マーケティング
***** ビジネス戦略と目標・評価
***** 経営管理システム

**** 技術戦略マネジメント
***** 技術開発戦略の立案
***** 技術開発計画

**** ビジネスインダストリ
***** ビジネスシステム
***** エンジニアリングシステム
***** e-ビジネス
***** 民生機器
***** 産業機器

*** 企業と法務
**** 企業活動
***** 経営・組織論
***** OR・IE
***** 会計・財務

**** 法務
***** 知的財産権
***** セキュリティの関連法規
***** 労働関連・取引関連法規
***** その他の法律・ガイドライン・技術者倫理
***** 標準化関連

@endmindmap
